### ISSUE TITLE
Issues to flash from arduino IDE

### ISSUE THREAD

**Issue by tusharvb19** [RAKWireless/RAK4600_Arduino#1]
I try to find the PIN 18, but it is already grounded! I am using RAK4600 Module and not the breakout board!
I am not able to flash the code from Arduino IDE using serial.
Also, I tried using J-Link(select as a programmer and then Upload using programmer) it flashed, but no results!
If I am putting RAK firmware hex via J-Link again, it works fine!
But, when I flashed code via Arduino by 1) Serial update is not working
2) J-Link is also not working

I am stuck!

**Comment by tusharvb19** [comment]
I checked, the bootloader is having an issue I guess,
If I flash from segger with examples, they are working with diff bootloader.

**Comment by tusharvb19** [comment]
It is working...
I just reflashed the RAK firmware and then using Arduino IDE and J-Link, flashed code as Upload using Programmer(J-Link as Programmer selected in Tools-->Programmer)

**Comment by Advait-Hortiya** [comment]
Hello @tusharvb19, Did you start the device in bootloader mode before uploading the bootloader with arduino IDE?

**Comment by tusharvb19** [comment]
@Advait-Hortiya I am currently using J-Link to flash the firmware and not the Serial method!
